# Generated by Django 4.0.6 on 2023-10-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seamanagercruiseuser',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
    ]
