# Generated by Django 4.0.6 on 2023-10-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seamanagercruiseuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
