# Generated by Django 4.0.6 on 2023-11-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seamanagercruiseuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seamanagercruiseuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='seamanagercruiseuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='seamanagercruiseuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seamanagercruiseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seamanagercruiseuser',
            name='last_name',
        ),
    ]
