# Generated by Django 4.0.6 on 2023-11-30 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_seamanagercruiseuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cruise_reservee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
