# Generated by Django 4.0.6 on 2023-11-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reservation_number_of_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='arrival_date_time',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='unique_cruise_number',
        ),
    ]
