# Generated by Django 4.0.6 on 2023-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cruise_arrival_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiselocation',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
