# Generated by Django 4.0.6 on 2023-12-01 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cruiselocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cruise_reservee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
