# Generated by Django 4.0.6 on 2024-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_reservation_cruise_reservee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='image_main',
            field=models.URLField(default='https://images.pexels.com/photos/813011/pexels-photo-813011.jpeg'),
        ),
    ]
