# Generated by Django 4.0.6 on 2024-01-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0011_cruise_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='seamanagercruiseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='seamanagercruiseuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='seamanagercruiseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
