# Generated by Django 4.0.6 on 2024-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_seamanagercruiseuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='captain',
            name='profile_picture',
            field=models.URLField(default='https://gcaptain.com/wp-content/uploads/2017/07/grumpy-ship-captain.jpeg'),
        ),
        migrations.AlterField(
            model_name='seamanagercruiseuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
