# Generated by Django 4.0.6 on 2024-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cruiselocation_description_cruiselocation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='age',
        ),
        migrations.AddField(
            model_name='cruise',
            name='image_1',
            field=models.URLField(default='https://media.istockphoto.com/id/458115989/photo/cruise-ship-in-caribbean-sea.jpg?s=612x612&w=0&k=20&c=wMweujKOnZOpihjorKHEdgqI-LDMJkLF-LpV_FhtUWE='),
        ),
        migrations.AddField(
            model_name='cruise',
            name='image_2',
            field=models.URLField(default='https://media.istockphoto.com/id/1222173565/photo/cruise-ship-msc-seaside-at-cozumel-island-mexico.jpg?s=612x612&w=0&k=20&c=2w3dQqb196mclsS-oMbFEgYl3r7jgQZFgvKYdASUEMs='),
        ),
        migrations.AddField(
            model_name='cruise',
            name='image_3',
            field=models.URLField(default='https://media.istockphoto.com/id/516463721/photo/3d-cruise-ship-in-beautiful-ocean-with-blue-sky.jpg?s=612x612&w=0&k=20&c=97aWdauUuFSZwMXZ6Ky4TZDuxg9vhjDb98wFj0vwL3s='),
        ),
        migrations.AddField(
            model_name='cruise',
            name='image_4',
            field=models.URLField(default='https://media.istockphoto.com/id/1155311911/photo/luxury-cruise-ship-sailing-from-the-port-at-sunrise-across-the-ocean-beautiful-summer.jpg?s=612x612&w=0&k=20&c=im3OvbdWWN-vdwcVcSFMGKpmpbB97Elj5Nva8UXJlmA='),
        ),
    ]
